### PR TITLE
DOCKER-351 Fix legacy images build

### PR DESCRIPTION
**Pull request by kerkhofsd**

### CODE REVIEW

**Review by todorinskiz — APPROVED** [review]

**Review by vierbergenlars — APPROVED** [review]
Verified that it builds a legacy image that does contain Alfresco

**Review by vierbergenlars — CHANGES_REQUESTED** [review]
Setting leanImage to true will prevent the baseShareWar from being added

**Review by vierbergenlars — APPROVED** [review]
In theory, this should work. (And it builds correctly locally, having both Alfresco and Share webapps loaded)

**Comment by vierbergenlars** [comment]
I have started a non-parallel build here to debug the build failure: https://jenkins-2.xenit.eu/job/Xenit%20Github/job/docker-alfresco/job/DOCKER-351/9/console

**Pull request merged**
