### PR TITLE
Fix build of Alfresco enterprise images on Xenit's build server

### PR DESCRIPTION
**Pull request by koenvangeerteruy**
Hello @anghelutar  ,

Due to the cleanup of init.gradle on Xenit's build server, the Alfresco enterprise images don't build anymore.

With the updates on docker-openjdk and docker-tomcat, I think it is a good idea to rebuild the docker-alfresco images so they contain the last openjdk and tomcat updates.

Question regarding all the branches in this project
Can I clean up (delete) all the branches that have been merged or closed?

Kind regards,
Koen

### CODE REVIEW

**Comment by anghelutar** [comment]
@koenvangeerteruy good idea to rebuild
Custodian (https://github.com/xenit-eu/custodian) would do this automatically, don't you want to automate this?

**Review by anghelutar — APPROVED** [review]

**Comment by koenvangeerteruy** [comment]
@anghelutar , yes I know Custodian would help with automating rebuilds when docker-tomcat and docker-openjdk have been updated.
At the moment we don't have this yet, so we need to do it manually. Triggering a build on Travis-CI and Xenit's build server is not that big of a deal.
However with every docker-openjdk update, docker-tomcat needs to be adapted as well. I think it would help when docker-tomcat also could be rebuild without any changes.

**Comment by anghelutar** [comment]
@tgeens implemented it like that because originally multiple combinations were supported in the alfresco stack. But later we moved away from alfresco supported stack (adopt openjdk + latest jdk), so I suppose tomcat could use a "latest" image for java and be re-triggered by a simple push of the button.

**Comment by koenvangeerteruy** [comment]
@anghelutar OK. Maybe that is something that can be discussed on the Architectural Board.

**Comment by koenvangeerteruy** [comment]
@tgeens, OK to merge?

**Review by tgeens — APPROVED** [review]

**Review by vierbergenlars — APPROVED** [review]
Thanks for getting rid of the jcenter repository here :+1:

**Comment by koenvangeerteruy** [comment]
> Thanks for getting rid of the jcenter repository here 👍

@vierbergenlars You are welcome. A bit of clean up from time to time doesn't hurt.

**Pull request merged**
