### PR TITLE
Align changelog with docker-openjdk and docker-tomcat

### PR DESCRIPTION
**Pull request by koenvangeerteruy**
Hello @anghelutar, @tgeens, @thijslemmens, @vierbergenlars,

With this PR I want to propose reformat the changelog more in line with the changelog of docker-openjdk and docker-tomcat.
I tried to give a better insight in the chronology of the changes.

docker-alfresco makes use of Xenit Version in the builds. Since Xenit Version has been introduced in 2020-03 the version has been stuck to version 1.0.1-SNAPSHOT and all changes were in Unreleased in the changelog. This caused we were losing the chronological information, which I think is also one of the reasons to keep a changelog. docker-alfresco does not have a release branch and all builds of the master branch are published to hub.docker.com and hub.xenit.eu, so I propose to set xenitVersion in gradle.properties to yyyy-mm.x, where x is the zero-based qualifier for the n-th release of that month.

I am not sure whether we want to keep the release date after the version or put it on the changelog entry like in docker-openjdk and docker-tomcat.

I like to hear your feedback.

Kind regards,
Koen

### CODE REVIEW

**Review by anghelutar — COMMENTED** [review]
There was a problem of not releasing anything since going public.
Changelog could contain date of the PR, to keep chronological Information.
I don’t think every PR should trigger a change in xenitVersion. I would not link this version with a date.

**Comment by koenvangeerteruy** [comment]
Hello @anghelutar, @tgeens and @thijslemmens

> There was a problem of not releasing anything since going public.
OK. I understand. Since there is no release branch, master builds are published. So I propose we consider master as the release branch for now and therefor don't use the qualifier -SNAPSHOT
> Changelog could contain date of the PR, to keep chronological Information.
OK. That's good
> I don’t think every PR should trigger a change in xenitVersion. I would not link this version with a date.
Yes, I agree. We should only put functional changes (i.e. changes reflected in the docker images) in the change log.
Changes to update the build pipeline tools and configuration or changes to the readme and changelog should not be entered in the changelog. To keep it clean.
If you prefer following more a semantic versioning scheme that's OK.
I would propose the following:
- major bump when image builds are removed
- minor bump when features are added or settings are changed
- micro bump when fixes are applied

I come to the following proposition of the versions:
## 2020-09.4 [v4.1.0] (2020-09-29)
### Changed
* [PR #50](https://github.com/xenit-eu/docker-alfresco/pull/50) DOCKER-311 Change requirements for `chown` in `90-init-alfresco.sh` to prevent costly chown operations

## 2020-09.3 [v4.0.0] (2020-09-21)
### Removed
* [PR #49](https://github.com/xenit-eu/docker-alfresco/pull/49) DOCKER-345 Disabled building of legacy Alfresco enterprise 5.0 images

## 2020-09.2 [v3.3.1] (2020-09-16)
### Fixed
* [PR #48](https://github.com/xenit-eu/docker-alfresco/pull/48) [Issue47](https://github.com/xenit-eu/docker-alfresco/issues/47) Fix ambiguity in envvar handling in java initscript

## 2020-09.1 [v3.3.0] (2020-09-15)
### Added
* [PR #46](https://github.com/xenit-eu/docker-alfresco/pull/46) DOCKER-344 Enabled building of legacy Alfresco enterprise 5.0 images

## 2020-09.0 [v3.2.0] (2020-09-01)
### Added
* [PR #44](https://github.com/xenit-eu/docker-alfresco/pull/44) [Issue43](https://github.com/xenit-eu/docker-alfresco/issues/43) DOCKER-341 Added configuration for custom ssl key- & truststores

## 2020-07.0 [v3.1.2] (2020-07-03)
### Fixed
* [PR #41](https://github.com/xenit-eu/docker-alfresco/pull/41) DOCKER-339 Init script was installing xmlstarlet and required internet connection

## 2020-05.1 [v3.1.1] (2020-05-29)
### Fixed
* [PR #38](https://github.com/xenit-eu/docker-alfresco/pull/38) DOCKER-335 Fix bug where `SOLR_SSL=none` deleted too much from server.xml

## 2020-05.0 [v3.1.0] (2020-05-26)
### Changed
* [PR #37](https://github.com/xenit-eu/docker-alfresco/pull/37) Update to last 5.2 (5.2.7.3 - added), 6.0 (6.0.1.3), 6.1 (6.1.1.3) and 6.2 (6.2.1 - added) versions

## 2020-04.0 [v3.0.1] (2020-04-17)
### Fixed
* [PR #34](https://github.com/xenit-eu/docker-alfresco/pull/34) DOCKER-321 Fix issues that the Tomcat SSL connector no longer configured since upgrade to latest version

## 2020-03.0 [v3.0.0] (2020-03-13)
### Added
* [PR #33](https://github.com/xenit-eu/docker-alfresco/pull/33) DOCKER-312 Start a release procedure: add Xenit version to the images tags

## 2020-02.1 [v2.6.0] (2020-02-24)
### Changed
* [PR #30](https://github.com/xenit-eu/docker-alfresco/pull/30) DOCKER-309 Update Alfresco Enterprise 6.1.0 to 6.1.1 

## 2020-02.0 [v2.5.0] (2020-02-10)
### Added
* [PR #28](https://github.com/xenit-eu/docker-alfresco/pull/28) DOCKER-284 Allow setting log levels through docker-compose

## 2019-12.1 [v2.4.0] (2019-12-05)
### Added
* [PR #25](https://github.com/xenit-eu/docker-alfresco/pull/25) DOCKER-294 Install fontconfig in the skeleton image

## 2019-12.0 [v2.3.0] (2019-12-02)
### Changed
* [PR #24](https://github.com/xenit-eu/docker-alfresco/pull/24) DOCKER-292 Bump versions transformers. Use transform router + queue based transformations.

## 2019-11.2 [v2.2.0] (2019-11-29)
### Added
* [PR #23](https://github.com/xenit-eu/docker-alfresco/pull/23) DOCKER-291 Added enterprise 6.2.0 and community 6.2.0-ga

## 2019-11.1 [v2.1.1] (2019-11-28)
### Fixed
* [PR #22](https://github.com/xenit-eu/docker-alfresco/pull/22) DOCKER-288 Make sure java executable points to AdoptOpenJDK

## 2019-11.0 [v2.1.0] (2019-11-05)
### Changed
* [PR #17](https://github.com/xenit-eu/docker-alfresco/pull/17) DOCKER-278 Move java specific variables (jmx, debug, memory settings) to java layer

## 2019-09.0 [v2.0.0] (2019-09-13)
### Added
* [PR #13](https://github.com/xenit-eu/docker-alfresco/pull/13) DOCKER-266 Added enterprise 5.2.6

### Changed
* [PR #11](https://github.com/xenit-eu/docker-alfresco/pull/11) DOCKER-263, DOCKER-259, DOCKER-258, DOCKER-257, DOCKER-256 Refactorings, better handling of failures, notifications
  * Increase number of tries in healthcheck
  * Use smartCopy functionality
  * Disable pulling image when using an image id

### Removed
* [PR #14](https://github.com/xenit-eu/docker-alfresco/pull/14) DOCKER-267 Removed enterprise 5.1.1, 5.2.0, 5.2.2 and 5.2.3

## [v1.1.0] - 2019-08-30
### Changed
* [DOCKER-236] Separate out share: see https://github.com/xenit-eu/docker-share
* [DOCKER-255] Continue to build some legacy images, with both Alfresco and Share inside
* [DOCKER-253] Move handling of properties to Java code instead of shell in the init

### Fixed
* [DOCKER-251] Init script was duplicating JAVA_OPTS_<var> variables

When OK for you. I will change to [vx.y.z] - yyyy-mm-dd format.

For you comments.

Kind regards,
Koen

**Comment by tgeens** [comment]
First of all, thank you for the hard work @koenvangeerteruy :-)

We decided in the AB yesterday that it would be best that we introduce a `release` branch. What that means for the existing changelog, needs to be figured out.

(That means also in the upstream images, we should move to a `release` branch)

**Comment by koenvangeerteruy** [comment]
Hello @tgeens,

I think it is a good decision to introduce a `release` branch for docker-alfresco as well as the upstream projects docker-tomcat and docker-openjdk, just like it is already for docker-postgres and alfred-api.
It gives Xenit more control about including changes and the release of the images for Xenit's usage.

For now docker-alfresco is the only project that is using `Xenit Version`. So, I think a semantic like versioning schema can be followed if you like.
As I understand it, all the already merged PR's to master have been published to hub.docker.com and hub.xenit.eu with Xenit Version = v1.0.1-SNAPSHOT.
We could release a v1.0.1 version when building on the release branch. I would propose to add the timestamps to the changelog entries like is done for docker-openjdk and docker-tomcat and release v1.0.1. Depending on how often images would be published in release we can group changes together like is done for alfred-api. Whether you want to keep a timestamp or not is for Xenit to decide.

I am open to your feedback.

Kind regards,
Koen

**Comment by anghelutar** [comment]
Xenit version is not really used at the moment, it is just a label in the image. 
The idea was to allow - based on this label - different characteristics / behaviours in client images, for example adding labels for filebeat to use json parsing (enabling json logging would only be available from a certain version on).

**Comment by tgeens** [comment]
The timestamps per changelog-entry are no longer useful if we use a `release` branch, right ?

**Comment by koenvangeerteruy** [comment]
Yes, the timestamps per changelog-entry can go away when using a `release` branch. You set the timestamp on the version when released, like is done for alfred-api.
I think the timestamps could be useful depending on the speed of release. I think we want to avoid what happened with the changelog for this project, all entries are logged in unreleased and you loose chronology and time.
If every time we release and publish a timestamp is added to the version it is OK. I think you want to have some feeling of when something was released in the changelog.

**Comment by anghelutar** [comment]
Is the quality of contributions high enough so that the Changelog can be automatically generated when making a release?
Is/are maintainer(s) dedicated enough to release frequently?
Is the community present enough to make PRs and raise issues?

Having timestamps per PR are a good idea imo.

**Review by anghelutar — APPROVED** [review]

**Pull request merged**
