### PR TITLE
[Docker 321] Tomcat SSL connector no longer configured since upgrade to latest version

### PR DESCRIPTION
**Pull request by hvancamp**
Make sure SSL connector is added again on latest versions of Tomcat.

### CODE REVIEW

**Comment by tgeens** [comment]
1. is there a way we can test the results of xmlstartlet or the impact ?
2. don't merge origin/master into your feature branch - use `git rebase origin/master` (we can squash that when merging, so it's ok now)

**Comment by hvancamp** [comment]
>     1. is there a way we can test the results of xmlstartlet or the impact ?

Yes, we can test if port 8443 is responding or not. That's what xmlstarlet is configuring in the end.

>     2. ok, my bad!

**Comment by hvancamp** [comment]
@tgeens found a quick way to verify if the xmlstarlet changes are applied by exposing the default SSL port in the Alfresco docker-compose. By doing so it automatically gets checked by the gradle docker-compose plugin, it verifies that every exposed port on a container is open.

**Comment by tgeens** [comment]
Nice

Wondering wether that does not break the "integrationTestChangedPorts" test

**Comment by hvancamp** [comment]
"integrationTestChangedPorts" is using a different compose file

**Comment by tgeens** [comment]
(It's a bit too implicit, but I need to figure out how to deal with that in docker-tomcat first)

**Pull request merged**
